### ISSUE TITLE
Image.py error

### ISSUE THREAD

**Issue by khoroshyy** [pfigliozzi/Phase#1]
Hi,
I have problems running it, using Anaconda 2 on win64
On the beginning I had an import error:
 ImportError: No module named _imagingtk 

After I followed these steps:
https://github.com/ContinuumIO/anaconda-issues/issues/150
and 
The following error appears:

D:\Phase-master>python main_gui.py
Traceback (most recent call last):
  File "main_gui.py", line 710, in <module>
    main_window(root)
  File "main_gui.py", line 132, in **init**
    self.disable_bounding_box_widgets()
  File "main_gui.py", line 149, in disable_bounding_box_widgets
    self.update_modified_mask_preview()
  File "main_gui.py", line 305, in update_modified_mask_preview
    resized_image = resized_image.resize((original_size \* resize_ratio).astype(i
nt), Image.NEAREST)
  File "C:\Anaconda2\lib\site-packages\PIL\Image.py", line 1550, in resize
    return self._new(self.im.resize(size, resample))
ValueError: height and width must be > 0

Can you recommend something?

**Comment by pfigliozzi** [comment]
I found the issue and fixed it in a50e07703a60b1d1311993c09a1bffda5206262d. If you download the new version of main_gui.py it should work.

**Comment by khoroshyy** [comment]
Thanks.
It is working.

---

Petro Khoroshyy
